module.exports=function(d){
const {get,set,remove,multiUpdate,db,useMemDb,crypto,CFG,nowIso,uid,encodeFirebaseKey,cleanEmail,EMAIL_RE,MOBILE_RE,hashPassword,passwordMatches,sendEmail,emailShell,escapeHtml,rateLimit,validateCsrf,createCsrfToken,setCsrfCookie,verifyAdminSession,verifyUserSession,createAdminSession,createUserSession,setSessionCookie,clearSessionCookie,body,send,publicUser,adminOtpState,ADMIN_OTP_TTL_MS,hashAdminOtp}=d;
const R='cem2',P={institutes:R+'/institutes',students:R+'/students',teachers:R+'/teachers',modules:R+'/modules',tests:R+'/tests',submissions:R+'/submissions',attempts:R+'/examAttempts',locks:R+'/attemptLocks',scores:R+'/scoreIndex',ratings:R+'/ratings',resets:R+'/passwordResets',settings:R+'/settings'};
const DEFAULT_MODULES=[['SSC','🏛️','CGL • CHSL • MTS • GD'],['Banking','🏦','IBPS • SBI • RBI'],['Railway','🚆','RRB NTPC • Group D'],['CTET / OTET','🎓','TET preparation'],['Odisha Exams','🌐','OSSC • OSSSC • OPSC • Police • Other exams'],['Defence','🪖','General preparation']];
const DEFAULT_SETTINGS={institutionName:'Competitive Exam Master',logoDataUrl:'',address:'',contactEmail:'',contactPhone:'',themeMode:'light',backgroundColor:'#f3f5f9',foregroundColor:'#172033',primaryColor:'#2563eb'};
const map=async p=>(await get(p))||{},key=v=>encodeURIComponent(String(v||'')),okUser=v=>/^[A-Za-z0-9][A-Za-z0-9._-]{3,39}$/.test(String(v||'')),okPass=v=>{const p=String(v||'');return p.length>=10&&p.length<=128&&/[A-Z]/.test(p)&&/[a-z]/.test(p)&&/[0-9]/.test(p);};
const pubInst=i=>{if(!i)return null;const x={...i};delete x.password;delete x.passwordHash;return x;};
const findUser=async email=>{const e=cleanEmail(email);for(const root of [P.students,P.teachers]){const m=await map(root),u=Object.values(m).find(x=>cleanEmail(x?.email)===e);if(u)return u;}return null;};
const load=(role,id)=>get((role==='student'?P.students:role==='teacher'?P.teachers:P.institutes)+'/'+key(id));
const settingsFor=i=>({...DEFAULT_SETTINGS,institutionName:i.institutionName,contactEmail:i.email,contactPhone:i.phone});
const summary=t=>({id:t.id,title:t.title,exam:t.exam,category:t.category,subjects:t.subjects||['General'],languages:t.languages?.length?t.languages:['English'],type:'free',attemptPolicy:t.attemptPolicy==='once'?'once':'reattempt',duration:t.duration,questionCount:t.questionCount,createdAt:t.createdAt,published:!!t.published});
async function seedInstitute(id){const mp=P.modules+'/'+key(id);if(!(await get(mp))){const m={};DEFAULT_MODULES.forEach((x,i)=>{const mid='m-default-'+(i+1);m[mid]={id:mid,name:x[0],icon:x[1],description:x[2],createdBy:'system',createdAt:nowIso()};});await set(mp,m);}if(!(await get(P.settings+'/'+key(id))))await set(P.settings+'/'+key(id),settingsFor(await get(P.institutes+'/'+key(id))));}
async function current(req,roles){const portal=String(req.headers['x-cem-portal']||'').toLowerCase(),c=parseCookies(req),token=portal==='admin'?c.cem_admin_session:portal==='institute'?c.cem_institute_session:portal==='student'?c.cem_user_session:(c.cem_user_session||c.cem_institute_session);const a=verifyAdminSession(token);if(a){if(roles&&!roles.includes('admin'))throw Object.assign(new Error('Not authorized.'),{status:403});return {uid:a.uid,user:{uid:a.uid,name:CFG.admin.name,email:CFG.admin.email,role:'admin',status:'approved',blocked:false}};}const s=verifyUserSession(token);if(!s)throw Object.assign(new Error('Please log in.'),{status:401});const u=await load(s.role,s.uid);if(!u)throw Object.assign(new Error('Account no longer exists. Please log in again.'),{status:401});if(u.blocked||['blocked','deleted'].includes(u.status))throw Object.assign(new Error('Your account has been blocked. Contact your institute administrator.'),{status:403});if(u.role==='institute'&&u.status!=='active')throw Object.assign(new Error('This institute account is not active.'),{status:403});if(u.role!=='institute'&&u.status!=='approved')throw Object.assign(new Error('Your account is waiting for institute approval.'),{status:403});if(roles&&!roles.includes(u.role))throw Object.assign(new Error('Not authorized.'),{status:403});if(u.role!=='institute'&&!u.instituteId)throw Object.assign(new Error('Your account is not linked to an institute.'),{status:403});return {uid:u.uid,user:u};}
function parseCookies(req){const o={};for(const x of String(req.headers.cookie||'').split(';')){const i=x.indexOf('=');if(i>0)o[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1).trim());}return o;}
async function register(req,res,role){const b=await body(req),email=cleanEmail(b.email),name=String(b.name||'').trim(),mobile=String(b.mobile||'').trim(),password=String(b.password||''),instituteId=String(b.instituteId||'').trim();rateLimit(req,'register-email',6,3600000,email);if(!name||!EMAIL_RE.test(email)||!MOBILE_RE.test(mobile)||!instituteId)throw new Error('Please complete all fields and choose your institute.');if(role==='teacher'&&!String(b.subject||'').trim())throw new Error('Please enter your subject or expertise.');if(!okPass(password))throw new Error('Password must be 10-128 characters and include uppercase, lowercase and a number.');const inst=await get(P.institutes+'/'+key(instituteId));if(!inst||inst.status!=='active')throw new Error('Please choose an active institute.');if(await findUser(email))throw new Error('This email is already registered.');const id=uid(role==='teacher'?'tch-':'std-'),u={uid:id,name,email,mobile,passwordHash:hashPassword(password),role,status:'pending',blocked:false,registrationComplete:true,instituteId,createdAt:nowIso()};if(role==='teacher')u.subject=String(b.subject).trim();await set((role==='teacher'?P.teachers:P.students)+'/'+id,u);return send(res,200,{message:role==='teacher'?'Teacher registration submitted. Wait for institute approval.':'Student registration submitted. Wait for institute approval.',user:publicUser(u)});}
async function calc(t,answers,times,save,u,sid){let score=0,correct=0,incorrect=0,unattempted=0;const sections={};const review=t.questions.map((q,i)=>{const given=answers[i]?String(answers[i]).toUpperCase():null,s=q.subject||'General',z=sections[s]||={section:s,score:0,correct:0,incorrect:0,attempted:0,total:0,maxScore:0};z.total++;z.maxScore+=Number(q.marks)||0;let outcome='unattempted';if(given){z.attempted++;if(given===q.answer){score+=Number(q.marks)||0;correct++;z.correct++;outcome='correct';}else{score-=Number(q.negative)||0;incorrect++;z.incorrect++;outcome='incorrect';}}else unattempted++;return {index:i,question:q.question,options:q.options,correctAnswer:q.answer,givenAnswer:given,outcome,explanation:q.explanation||''};});score=Math.round(score*100)/100;const maxScore=Math.round(t.questions.reduce((a,q)=>a+(Number(q.marks)||0),0)*100)/100,attempted=correct+incorrect,accuracy=attempted?Math.round(correct/attempted*1000)/10:0,sec=Object.values(sections).map(x=>({...x,score:Math.round(x.score*100)/100,maxScore:Math.round(x.maxScore*100)/100,accuracy:x.attempted?Math.round(x.correct/x.attempted*1000)/10:0,timeSeconds:Number(times?.[x.section]??times?.[encodeFirebaseKey(x.section)]??0)||0}));if(save){const saved={id:sid,testId:t.id,userId:u.uid,instituteId:u.instituteId,score,answers,timeBySubject:times,submittedAt:nowIso(),integrity:{serverCalculated:true,submissionId:sid}};await multiUpdate({[P.submissions+'/'+sid]:saved,[P.scores+'/'+t.id+'/'+sid]:{score,userId:u.uid,submittedAt:saved.submittedAt}});}const scores=Object.values(await map(P.scores+'/'+key(t.id))).map(x=>Number(x?.score)||0),rank=scores.filter(x=>x>score).length+1,below=scores.filter(x=>x<score).length,percentile=scores.length>1?Math.round(below/(scores.length-1)*1000)/10:100;return {testId:t.id,title:t.title,score,maxScore,correct,incorrect,unattempted,attempted,total:t.questions.length,accuracy,rank,totalAttempts:scores.length,percentile,sections:sec,review};}
function ratingPublic(r){return r?{id:r.id,testId:r.testId,testTitle:r.testTitle||'',userId:r.userId,userName:r.userName||'',rating:r.rating,feedback:r.feedback||'',createdAt:r.createdAt,updatedAt:r.updatedAt}:null;}
return async function route(req,res){
const url=new URL(req.url,'http://localhost'),method=req.method;if(method==='OPTIONS')return send(res,204,{});
if(url.pathname==='/api/auth/csrf'&&method==='GET'){const token=createCsrfToken();setCsrfCookie(res,token);return send(res,200,{csrfToken:token});}
if(url.pathname.startsWith('/api/')&&method!=='GET'){rateLimit(req,'api-global-v2',180,60000);validateCsrf(req);}
if(url.pathname==='/api/config'&&method==='GET')return send(res,200,{authMode:'manual',architecture:'institute-v2',paymentEnabled:false});
if(url.pathname==='/api/health'&&method==='GET')return send(res,200,{ok:true,status:'online',port:CFG.port});

if(url.pathname==='/api/admin/request-otp'&&method==='POST'){const b=await body(req),email=cleanEmail(b.email);rateLimit(req,'admin-otp',5,900000,email);if(email!==CFG.admin.email)throw Object.assign(new Error('This email is not authorized for Main Admin access.'),{status:403});if(Date.now()-adminOtpState.sentAt<60000)throw Object.assign(new Error('Please wait 60 seconds before requesting another OTP.'),{status:429});const otp=String(crypto.randomInt(100000,1000000));adminOtpState.hash=hashAdminOtp(otp);adminOtpState.expiresAt=Date.now()+ADMIN_OTP_TTL_MS;adminOtpState.attempts=0;adminOtpState.sentAt=Date.now();if(!await sendEmail(CFG.admin.email,'Competitive Exam Master Main Admin OTP',emailShell('Main Admin login verification','<p>Your one-time Main Admin OTP is:</p><div style="font-size:32px;font-weight:800;letter-spacing:8px;padding:14px 0">'+otp+'</div><p>This code expires in 10 minutes.</p>')))throw Object.assign(new Error('Admin OTP email delivery is unavailable right now.'),{status:503});return send(res,200,{message:'OTP sent.'});}
if(url.pathname==='/api/admin/verify-otp'&&method==='POST'){const b=await body(req),email=cleanEmail(b.email),otp=String(b.otp||'');rateLimit(req,'admin-otp-verify',8,900000,email);if(email!==CFG.admin.email||!/^d{6}$/.test(otp)||!adminOtpState.hash||Date.now()>adminOtpState.expiresAt||adminOtpState.attempts>=5)throw Object.assign(new Error('Invalid or expired OTP.'),{status:401});adminOtpState.attempts++;const a=Buffer.from(hashAdminOtp(otp)),z=Buffer.from(adminOtpState.hash);if(a.length!==z.length||!crypto.timingSafeEqual(a,z))throw Object.assign(new Error('Invalid or expired OTP.'),{status:401});adminOtpState.hash='';setSessionCookie(res,createAdminSession('admin-cem-master'),'admin');return send(res,200,{message:'Main Admin login successful.',user:{uid:'admin-cem-master',name:CFG.admin.name,email:CFG.admin.email,role:'admin'}});}
if(url.pathname==='/api/auth/me'&&method==='GET'){try{const p=String(req.headers['x-cem-portal']||'').toLowerCase(),roles=p==='admin'?['admin']:p==='institute'?['institute']:p==='student'?['student','teacher']:undefined;const {user}=await current(req,roles);return send(res,200,{user:publicUser(user)});}catch(e){if(Number(e.status)===401)return send(res,200,{user:null});throw e;}}

if(url.pathname==='/api/institutes'&&method==='GET'){const list=Object.values(await map(P.institutes)).filter(i=>i?.status==='active').sort((a,b)=>String(a.institutionName).localeCompare(String(b.institutionName)));return send(res,200,{institutes:list.map(i=>({id:i.id,name:i.institutionName,head:i.head,email:i.email,phone:i.phone}))});}
if(url.pathname==='/api/main-admin/institutes'&&method==='GET'){await current(req,['admin']);return send(res,200,{institutes:Object.values(await map(P.institutes)).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).map(pubInst)});}
if(url.pathname==='/api/main-admin/institutes'&&method==='POST'){await current(req,['admin']);const b=await body(req),institutionName=String(b.institutionName||'').replace(/s+/g,' ').trim(),email=cleanEmail(b.email),head=String(b.head||'').replace(/s+/g,' ').trim(),phone=String(b.phone||'').trim(),username=String(b.username||'').trim(),password=String(b.password||'');if(institutionName.length<3||institutionName.length>120||!EMAIL_RE.test(email)||head.length<2||!MOBILE_RE.test(phone))throw new Error('Please provide valid institute details.');if(!okUser(username)||!okPass(password))throw new Error('Invalid institute User ID or password.');const all=await map(P.institutes);if(Object.values(all).some(i=>String(i.loginUsername||'').toLowerCase()===username.toLowerCase()))throw new Error('That institute User ID is already in use.');if(Object.values(all).some(i=>cleanEmail(i.email)===email&&i.status!=='deleted'))throw new Error('That institute email is already registered.');const id=uid('ins-'),inst={id,institutionName,email,head,phone,loginUsername:username,passwordHash:hashPassword(password),role:'institute',status:'active',createdAt:nowIso()};await set(P.institutes+'/'+id,inst);await seedInstitute(id);return send(res,200,{message:'Institute created successfully.',institute:pubInst(inst)});}
const rm=url.pathname.match(/^/api/main-admin/institutes/([^/]+)$/);if(rm&&method==='DELETE'){await current(req,['admin']);const id=decodeURIComponent(rm[1]),inst=await get(P.institutes+'/'+key(id));if(!inst)throw new Error('Institute not found.');inst.status='deleted';inst.deletedAt=nowIso();await set(P.institutes+'/'+key(id),inst);const [s,t]=await Promise.all([map(P.students),map(P.teachers)]),u={};for(const [id2,x] of Object.entries(s))if(x?.instituteId===id)u[P.students+'/'+id2+'/status']='blocked';for(const [id2,x] of Object.entries(t))if(x?.instituteId===id)u[P.teachers+'/'+id2+'/status']='blocked';if(Object.keys(u).length)await multiUpdate(u);return send(res,200,{message:'Institute removed. Its accounts are blocked and exam data is retained for audit.'});}

if(url.pathname==='/api/auth/register/student'&&method==='POST')return register(req,res,'student');
if(url.pathname==='/api/auth/register/teacher'&&method==='POST')return register(req,res,'teacher');
if(url.pathname==='/api/auth/login'&&method==='POST'){const b=await body(req),login=String(b.email||b.username||'').trim(),password=String(b.password||'');rateLimit(req,'login-v2',8,900000,login);let u=null,role='';const im=await map(P.institutes);u=Object.values(im).find(i=>String(i.loginUsername||'').toLowerCase()===login.toLowerCase());if(u)role='institute';if(!u){u=await findUser(login);if(u)role=u.role;}if(!u||!passwordMatches(password,u))throw Object.assign(new Error('Invalid login credentials.'),{status:401});if(u.blocked||['blocked','deleted'].includes(u.status))throw Object.assign(new Error('Your account has been blocked. Contact your institute administrator.'),{status:403});if(role==='institute'&&u.status!=='active')throw Object.assign(new Error('This institute account is not active.'),{status:403});if(role!=='institute'&&u.status!=='approved')throw Object.assign(new Error('Your account is waiting for institute approval.'),{status:403});setSessionCookie(res,createUserSession(u.uid,u.email||u.loginUsername,u.role,u.name||u.institutionName,u.instituteId||''),role==='institute'?'institute':'student');return send(res,200,{message:'Login successful.',user:publicUser(u)});}
if(url.pathname==='/api/auth/logout'&&method==='POST'){clearSessionCookie(res,String(req.headers['x-cem-portal']||''));return send(res,200,{message:'Logged out.'});}

if(url.pathname==='/api/account/me'&&method==='GET'){const {user}=await current(req,['student','teacher']);return send(res,200,{user:publicUser(user)});}
if(url.pathname==='/api/account/me'&&method==='PUT'){const {user}=await current(req,['student','teacher']),b=await body(req),u={...user};if(b.name!==undefined)u.name=String(b.name).trim();if(b.mobile!==undefined){u.mobile=String(b.mobile).trim();if(u.mobile&&!MOBILE_RE.test(u.mobile))throw new Error('Invalid mobile number.');}if(user.role==='teacher'&&b.subject!==undefined)u.subject=String(b.subject).trim();u.updatedAt=nowIso();await set((user.role==='teacher'?P.teachers:P.students)+'/'+user.uid,u);return send(res,200,{message:'Account updated.',user:publicUser(u)});}
if(url.pathname==='/api/account/email'&&method==='PUT'){
  const {user}=await current(req,['student','teacher']),b=await body(req),email=cleanEmail(b.email),currentPassword=String(b.currentPassword||'');
  if(!EMAIL_RE.test(email))throw new Error('Enter a valid new email address.');
  if(!passwordMatches(currentPassword,user))throw Object.assign(new Error('Current password is incorrect.'),{status:401});
  const existing=await findUser(email);if(existing&&existing.uid!==user.uid)throw new Error('This email is already registered.');
  const u={...user,email,passwordHash:hashPassword(currentPassword),updatedAt:nowIso()};
  await set((user.role==='teacher'?P.teachers:P.students)+'/'+user.uid,u);
  setSessionCookie(res,createUserSession(user.uid,email,user.role,user.name,user.instituteId||''),'student');
  return send(res,200,{message:'Login email changed successfully.',user:publicUser(u)});
}
if(url.pathname==='/api/account/password'&&method==='PUT'){const {user}=await current(req,['student','teacher']),b=await body(req);if(!passwordMatches(String(b.currentPassword||''),user))throw Object.assign(new Error('Current password is incorrect.'),{status:401});if(!okPass(b.newPassword))throw new Error('New password must be 10-128 characters and include uppercase, lowercase and a number.');await set((user.role==='teacher'?P.teachers:P.students)+'/'+user.uid,{...user,passwordHash:hashPassword(b.newPassword),updatedAt:nowIso()});return send(res,200,{message:'Password changed successfully.'});}

if(url.pathname==='/api/auth/forgot/request'&&method==='POST'){
  const b=await body(req),email=cleanEmail(b.email);rateLimit(req,'forgot-email',4,1800000,email);if(!EMAIL_RE.test(email))throw new Error('Enter a valid email address.');
  const u=await findUser(email);
  if(u){const otp=String(crypto.randomInt(100000,1000000));await set(P.resets+'/'+u.uid,{hash:crypto.createHmac('sha256',AUTH_SESSION_SECRET).update(otp).digest('hex'),expiresAt:Date.now()+600000,attempts:0});const sent=await sendEmail(email,'Competitive Exam Master password reset',emailShell('Password reset','<p>Your password reset code is:</p><div style="font-size:32px;font-weight:800;letter-spacing:8px;padding:14px 0">'+otp+'</div><p>This code expires in 10 minutes.</p>'));if(!sent)throw Object.assign(new Error('Email delivery is unavailable right now.'),{status:503});}
  return send(res,200,{message:'If an account exists for that email, a reset code has been sent.'});
}
if(url.pathname==='/api/auth/forgot/confirm'&&method==='POST'){
  const b=await body(req),email=cleanEmail(b.email),otp=String(b.otp||''),newPassword=String(b.newPassword||'');rateLimit(req,'forgot-confirm-email',8,1800000,email);const u=await findUser(email);if(!u)throw Object.assign(new Error('Invalid or expired reset request.'),{status:400});if(!okPass(newPassword))throw new Error('New password must be 10-128 characters and include uppercase, lowercase and a number.');
  const reset=await get(P.resets+'/'+u.uid),stored=String(reset?.hash||''),hash=crypto.createHmac('sha256',AUTH_SESSION_SECRET).update(otp).digest('hex');if(!reset||Date.now()>Number(reset.expiresAt)||Number(reset.attempts||0)>=5)throw Object.assign(new Error('Invalid or expired reset code.'),{status:400});reset.attempts=Number(reset.attempts||0)+1;await set(P.resets+'/'+u.uid,reset);const a=Buffer.from(hash),z=Buffer.from(stored);if(!/^\d{6}$/.test(otp)||a.length!==z.length||!crypto.timingSafeEqual(a,z))throw Object.assign(new Error('Invalid or expired reset code.'),{status:400});
  await set((u.role==='teacher'?P.teachers:P.students)+'/'+u.uid,{...u,passwordHash:hashPassword(newPassword),updatedAt:nowIso()});await remove(P.resets+'/'+u.uid);return send(res,200,{message:'Password reset successfully. You can now sign in.'});
}
if(url.pathname==='/api/institute/dashboard'&&method==='GET'){const {user:i}=await current(req,['institute']),[s,t,m,tests]=await Promise.all([map(P.students),map(P.teachers),map(P.modules+'/'+key(i.id)),map(P.tests)]);return send(res,200,{institute:pubInst(i),counts:{students:Object.values(s).filter(x=>x?.instituteId===i.id).length,teachers:Object.values(t).filter(x=>x?.instituteId===i.id).length,modules:Object.keys(m).length,tests:Object.values(tests).filter(x=>x?.instituteId===i.id).length}});}
if(url.pathname==='/api/institute/users'&&method==='GET'){const {user:i}=await current(req,['institute']),[s,t]=await Promise.all([map(P.students),map(P.teachers)]),f=x=>x?.instituteId===i.id,students=Object.values(s).filter(f).map(publicUser),teachers=Object.values(t).filter(f).map(publicUser);return send(res,200,{students,teachers,counts:{students:students.length,teachers:teachers.length,pendingStudents:students.filter(x=>x.status==='pending').length,pendingTeachers:teachers.filter(x=>x.status==='pending').length}});}
const ia=url.pathname.match(/^/api/institute/users/([^/]+)/(approve|block)$/);if(ia&&method==='POST'){const {user:i}=await current(req,['institute']),id=decodeURIComponent(ia[1]),action=ia[2],b=await body(req);let u=await get(P.students+'/'+id),root=P.students;if(!u){u=await get(P.teachers+'/'+id);root=P.teachers;}if(!u||u.instituteId!==i.id)throw Object.assign(new Error('User not found in this institute.'),{status:404});if(action==='approve')u.status=b.approved===false?'rejected':'approved';else{u.blocked=!!b.blocked;u.status=u.blocked?'blocked':'approved';}await set(root+'/'+id,u);if(action==='approve'&&u.status==='approved')await sendEmail(u.email,'Institute account approved',emailShell('Account approved','<p>Your '+escapeHtml(u.role)+' account at <b>'+escapeHtml(i.institutionName)+'</b> has been approved.</p>'));return send(res,200,{message:'Account updated.',user:publicUser(u)});}
const ide=url.pathname.match(/^/api/institute/users/([^/]+)$/);if(ide&&method==='DELETE'){const {user:i}=await current(req,['institute']),id=decodeURIComponent(ide[1]);let u=await get(P.students+'/'+id),root=P.students;if(!u){u=await get(P.teachers+'/'+id);root=P.teachers;}if(!u||u.instituteId!==i.id)throw Object.assign(new Error('User not found in this institute.'),{status:404});if(u.role==='teacher'){const tests=await map(P.tests);for(const t of Object.values(tests))if(t?.instituteId===i.id&&t.createdById===id){t.published=false;t.ownerRemovedAt=nowIso();await set(P.tests+'/'+t.id,t);}}await remove(root+'/'+id);return send(res,200,{message:'User deleted.'});}

if(url.pathname==='/api/settings'&&method==='GET'){let iid=String(url.searchParams.get('instituteId')||'');try{const {user}=await current(req);if(user.role!=='admin')iid=user.instituteId||iid;}catch(_){}if(iid){const i=await get(P.institutes+'/'+key(iid));if(!i||i.status!=='active')throw Object.assign(new Error('Institute not found.'),{status:404});return send(res,200,{settings:(await get(P.settings+'/'+key(iid)))||settingsFor(i)});}return send(res,200,{settings:DEFAULT_SETTINGS});}
if(url.pathname==='/api/settings'&&method==='PUT'){const {user:i}=await current(req,['institute']),b=await body(req),s={...(await get(P.settings+'/'+key(i.id))||settingsFor(i))};for(const k of ['backgroundColor','foregroundColor','primaryColor'])if(b[k]!==undefined&&!/^#[0-9a-f]{6}$/i.test(String(b[k])))throw new Error(k+' must be a 6-digit hex color.');for(const k of ['address','contactEmail','contactPhone'])if(b[k]!==undefined)s[k]=String(b[k]).trim();if(b.logoDataUrl!==undefined){if(b.logoDataUrl&&!/^data:image\/(png|jpe?g|webp);base64,/i.test(String(b.logoDataUrl)))throw new Error('Logo must be a PNG, JPG or WebP image.');if(String(b.logoDataUrl).length>2800000)throw new Error('Logo image is too large.');s.logoDataUrl=String(b.logoDataUrl);}if(b.themeMode!==undefined)s.themeMode=b.themeMode==='dark'?'dark':'light';s.institutionName=i.institutionName;s.contactEmail=s.contactEmail||i.email;s.contactPhone=s.contactPhone||i.phone;await set(P.settings+'/'+key(i.id),s);return send(res,200,{message:'Institute settings updated.',settings:s});}

if(url.pathname==='/api/modules'&&method==='GET'){const {user}=await current(req),iid=user.instituteId||user.id,mods=Object.values(await map(P.modules+'/'+key(iid))),tests=Object.values(await map(P.tests));return send(res,200,{modules:mods.map(m=>({...m,testCount:tests.filter(t=>t?.instituteId===iid&&t.category===m.name).length}))});}
if(url.pathname==='/api/modules'&&method==='POST'){const {user:i}=await current(req,['institute']),b=await body(req),name=String(b.name||'').replace(/s+/g,' ').trim();if(!name||name.length>40)throw new Error('Module name is required and must be 40 characters or less.');const p=P.modules+'/'+key(i.id),mods=await map(p);if(Object.values(mods).some(m=>m.name.toLowerCase()===name.toLowerCase()))throw new Error('That module already exists.');const m={id:uid('m-'),name,icon:Array.from(String(b.icon||'📘').trim()).slice(0,2).join('')||'📘',description:String(b.description||'').trim().slice(0,120),createdBy:i.loginUsername,createdAt:nowIso()};mods[m.id]=m;await set(p,mods);return send(res,200,{message:'Module added.',module:m});}
const md=url.pathname.match(/^/api/modules/([^/]+)$/);if(md&&method==='DELETE'){const {user:i}=await current(req,['institute']),id=decodeURIComponent(md[1]),p=P.modules+'/'+key(i.id),mods=await map(p);if(!mods[id])throw new Error('Module not found.');const tests=await map(P.tests);for(const t of Object.values(tests))if(t?.instituteId===i.id&&t.category===mods[id].name){t.published=false;t.moduleRemovedAt=nowIso();await set(P.tests+'/'+t.id,t);}delete mods[id];await set(p,mods);return send(res,200,{message:'Module removed and related tests unpublished.'});}

if(url.pathname==='/api/tests'&&method==='GET'){const {user}=await current(req),iid=user.instituteId||user.id,all=Object.values(await map(P.tests)).filter(t=>t?.instituteId===iid&&(user.role==='institute'||t.published)),mods=Object.values(await map(P.modules+'/'+key(iid))),sub=Object.values(await map(P.submissions)),attemptedIds=[...new Set(sub.filter(s=>s.userId===user.uid&&s.instituteId===iid).map(s=>s.testId))],cat=url.searchParams.get('category'),tests=cat?all.filter(t=>t.category===cat):all;return send(res,200,{tests:tests.map(summary),attemptedIds,categories:mods.map(m=>m.name)});}
if(url.pathname==='/api/tests/mine'&&method==='GET'){const {user}=await current(req,['teacher']);return send(res,200,{tests:Object.values(await map(P.tests)).filter(t=>t?.instituteId===user.instituteId&&t.createdById===user.uid).map(summary)});}
if(url.pathname==='/api/tests/all'&&method==='GET'){const {user:i}=await current(req,['institute']);const tests=Object.values(await map(P.tests)).filter(t=>t?.instituteId===i.id),subs=Object.values(await map(P.submissions)),counts={};subs.forEach(s=>{if(s.instituteId===i.id)counts[s.testId]=(counts[s.testId]||0)+1;});return send(res,200,{tests:tests.map(t=>({...summary(t),createdBy:t.createdBy,attempts:counts[t.id]||0}))});}
const am=url.pathname.match(/^/api/tests/([^/]+)/attempts$/);if(am&&method==='POST'){const {user}=await current(req,['teacher','institute']),t=await get(P.tests+'/'+decodeURIComponent(am[1]));if(!t||t.instituteId!==user.instituteId)throw new Error('Test series not found.');if(user.role==='teacher'&&t.createdById!==user.uid)throw new Error('Not authorized.');t.attemptPolicy=(await body(req)).attemptPolicy==='once'?'once':'reattempt';await set(P.tests+'/'+t.id,t);return send(res,200,{message:'Attempt policy updated.',test:summary(t)});}

const tm=url.pathname.match(/^/api/tests/([^/]+)(?:/(solution|submit|start))?$/);
if(tm&&method==='GET'&&!tm[2]){const {user}=await current(req,['student']),t=await get(P.tests+'/'+decodeURIComponent(tm[1]));if(!t||!t.published||t.instituteId!==user.instituteId)throw Object.assign(new Error('Test not found.'),{status:404});if(await attemptBlocked(t,user))throw new Error('You have already attempted this test. Only one attempt is allowed for this test series.');return send(res,200,summary(t));}
if(tm&&method==='POST'&&tm[2]==='start'){const {user}=await current(req,['student']),t=await get(P.tests+'/'+decodeURIComponent(tm[1]));if(!t||!t.published||t.instituteId!==user.instituteId)throw Object.assign(new Error('Test not found.'),{status:404});if(await attemptBlocked(t,user))throw Object.assign(new Error('You have already attempted this test. Only one attempt is allowed for this test series.'),{status:409});const id=crypto.randomBytes(24).toString('base64url'),started=Date.now(),ms=Math.max(60000,Math.min(Number(t.duration)||30,1440)*60000),a={id,testId:t.id,userId:user.uid,instituteId:user.instituteId,startedAt:new Date(started).toISOString(),expiresAt:new Date(started+ms).toISOString(),status:'active',questionCount:t.questions.length};await set(P.attempts+'/'+id,a);return send(res,200,{...summary(t),attemptId:id,serverStartedAt:a.startedAt,serverExpiresAt:a.expiresAt,questions:t.questions.map((q,i)=>({index:i,question:q.question,options:q.options,subject:q.subject||'General',marks:q.marks,negative:q.negative,translations:q.translations||{}}))});}
if(tm&&method==='GET'&&tm[2]==='solution'){const {user}=await current(req,['student']),t=await get(P.tests+'/'+decodeURIComponent(tm[1]));if(!t||t.instituteId!==user.instituteId)throw new Error('Test not found.');const saved=Object.values(await map(P.submissions)).filter(s=>s.testId===t.id&&s.userId===user.uid&&s.instituteId===user.instituteId).sort((a,b)=>new Date(a.submittedAt)-new Date(b.submittedAt)).at(-1);if(!saved)throw new Error('Attempt this test first to view its solution.');return send(res,200,await calc(t,saved.answers||{},saved.timeBySubject||{},false,user,''));}
if(tm&&method==='POST'&&tm[2]==='submit'){const {user}=await current(req,['student']),t=await get(P.tests+'/'+decodeURIComponent(tm[1]));if(!t||!t.published||t.instituteId!==user.instituteId)throw new Error('Test not found.');const b=await body(req),aid=String(b.attemptId||'').trim();if(!/^[A-Za-z0-9_-]{24,100}$/.test(aid))throw Object.assign(new Error('Invalid exam session.'),{status:400});const a=await get(P.attempts+'/'+aid);if(!a||a.testId!==t.id||a.userId!==user.uid||a.instituteId!==user.instituteId||a.status!=='active')throw Object.assign(new Error('Exam session is invalid or already submitted.'),{status:409});const now=Date.now(),expires=new Date(a.expiresAt).getTime();if(!Number.isFinite(expires)||now>expires+15000)throw Object.assign(new Error('Exam time has expired. Your attempt can no longer be submitted.'),{status:409});const raw=b.answers&&typeof b.answers==='object'&&!Array.isArray(b.answers)?b.answers:{},answers={};for(let i=0;i<t.questions.length;i++){const v=String(raw[i]??'').trim().toUpperCase();if(/^[ABCD]$/.test(v))answers[i]=v;}const rawTimes=b.timeBySubject&&typeof b.timeBySubject==='object'&&!Array.isArray(b.timeBySubject)?b.timeBySubject:{},times={};for(const s of(t.subjects||['General'])){const v=Number(rawTimes[s]??rawTimes[encodeFirebaseKey(s)]);if(Number.isFinite(v)&&v>=0)times[encodeFirebaseKey(s)]=Math.min(v,(Number(t.duration)||30)*60);}const sid='att-'+crypto.createHash('sha256').update(user.uid+'|'+t.id+'|'+aid).digest('hex').slice(0,40);if(t.attemptPolicy==='once'){const lp=P.locks+'/'+key(t.id)+'/'+key(user.uid);if(db&&!useMemDb){const tx=await db.ref(lp).transaction(cur=>cur===null?{attemptId:aid,submissionId:sid,createdAt:nowIso()}:undefined,undefined,false);if(!tx.committed){const old=await get(P.submissions+'/'+sid);if(old)return send(res,200,await calc(t,old.answers||{},old.timeBySubject||{},false,user,''));throw Object.assign(new Error('You have already attempted this test. Only one attempt is allowed for this test series.'),{status:409});}}else{const oldLock=await get(lp);if(oldLock)throw Object.assign(new Error('You have already attempted this test. Only one attempt is allowed for this test series.'),{status:409});await set(lp,{attemptId:aid,submissionId:sid,createdAt:nowIso()});}}try{const result=await calc(t,answers,times,true,user,sid);a.status='submitted';a.submittedAt=nowIso();a.serverElapsedSeconds=Math.max(0,Math.min((now-new Date(a.startedAt).getTime())/1000,(Number(t.duration)||30)*60));await update(P.attempts+'/'+aid,a);return send(res,200,result);}catch(e){if(t.attemptPolicy==='once')try{await remove(P.locks+'/'+key(t.id)+'/'+key(user.uid));}catch(_){}throw e;}}
if(url.pathname==='/api/tests'&&method==='POST'){const {user}=await current(req,['teacher']),b=await body(req),mods=await map(P.modules+'/'+key(user.instituteId));if(!Object.values(mods).some(m=>m.name===String(b.category||'')))throw new Error('Please choose a valid exam module from your institute.');if(!b.title||!Array.isArray(b.questions)||!b.questions.length)throw new Error('Test title and at least one question are required.');const subjects=[...new Set((Array.isArray(b.subjects)?b.subjects:['General']).map(String).map(x=>x.trim()).filter(Boolean))],languages=[...new Set((Array.isArray(b.languages)?b.languages:['English']).map(String).map(x=>x.trim()).filter(Boolean))],secondary=languages.slice(1),qs=[];b.questions.forEach((q,i)=>{const question=String(q.question||'').trim(),options=Array.isArray(q.options)?q.options.map(x=>String(x).trim()):[],answer=String(q.answer||'').toUpperCase();if(!question||question.length>5000||options.length!==4||options.some(x=>!x||x.length>1000)||!['A','B','C','D'].includes(answer))throw new Error('Question '+(i+1)+' is invalid.');const translations={};for(const lang of secondary){const tr=q.translations?.[lang];if(tr&&(tr.question||tr.options?.some(Boolean)))translations[lang]={question:String(tr.question||'').slice(0,5000),options:[0,1,2,3].map(k=>String(tr.options?.[k]||'').slice(0,1000))};}qs.push({question,options,answer,subject:String(q.subject||'General').trim()||'General',marks:Number.isFinite(Number(q.marks))?Math.max(0,Number(q.marks)):1,negative:Number.isFinite(Number(q.negative))?Math.max(0,Number(q.negative)):0,explanation:String(q.explanation||'').slice(0,5000),translations});});const t={id:uid('T'),title:String(b.title).trim().slice(0,160),exam:String(b.exam||'Competitive Exam').trim().slice(0,120),category:String(b.category),subjects,languages,type:'free',duration:Math.max(1,Math.min(Number.parseInt(b.duration,10)||30,1440)),questions:qs,questionCount:qs.length,createdBy:user.email,createdById:user.uid,instituteId:user.instituteId,createdAt:nowIso(),published:true,attemptPolicy:b.attemptPolicy==='once'?'once':'reattempt'};await set(P.tests+'/'+t.id,t);return send(res,200,{message:'Test Series added successfully and published.',test:summary(t)});}
const del=url.pathname.match(/^/api/tests/([^/]+)$/);if(del&&method==='DELETE'){const {user}=await current(req,['teacher','institute']),id=decodeURIComponent(del[1]),t=await get(P.tests+'/'+id);if(!t||t.instituteId!==user.instituteId)throw new Error('Test series not found.');if(user.role==='teacher'&&t.createdById!==user.uid)throw new Error('Not authorized.');await remove(P.tests+'/'+id);return send(res,200,{message:'Test series deleted.'});}
if(url.pathname==='/api/tests/rating'&&method==='POST'){const {user}=await current(req,['student']),b=await body(req),testId=String(b.testId||''),rating=Number(b.rating),feedback=String(b.feedback||'').trim().slice(0,1000),t=await get(P.tests+'/'+testId);if(!Number.isInteger(rating)||rating<1||rating>5||!t||t.instituteId!==user.instituteId)throw new Error('Invalid test rating.');const has=Object.values(await map(P.submissions)).some(x=>x.testId===testId&&x.userId===user.uid&&x.instituteId===user.instituteId);if(!has)throw Object.assign(new Error('Complete the test before rating it.'),{status:403});const all=await map(P.ratings),old=Object.values(all).find(x=>x.testId===testId&&x.userId===user.uid),row=old||{id:uid('rate-'),testId,testTitle:t.title,userId:user.uid,userName:user.name,instituteId:user.instituteId,createdAt:nowIso()};row.rating=rating;row.feedback=feedback;row.updatedAt=nowIso();await set(P.ratings+'/'+row.id,row);return send(res,200,{message:'Rating saved.',rating:ratingPublic(row)});}
if(url.pathname==='/api/tests/ratings/mine'&&method==='GET'){const {user}=await current(req,['student']),id=String(url.searchParams.get('testId')||''),all=await map(P.ratings);return send(res,200,{rating:ratingPublic(Object.values(all).find(x=>x.testId===id&&x.userId===user.uid&&x.instituteId===user.instituteId)||null)});}
return send(res,404,{error:'Not found.'});
};
};